### ISSUE TITLE
SMS button submit 2 times by clicking -> sms failed by sms provider block the sms

### ISSUE THREAD

**Issue by nqnhat1988** [lanhnguyen2010/trash#4]
SMS Provider sẽ block sms cùng 1 nội dung đến 1 số trong 5 phút -> request send sms bị failed ở click thứ 2 -> không thể đi qua màn hình OTP

Solution: Disable nút submit khi nhận click và enable lại + show lỗi khi có lỗi

**Comment by lanhnguyen2010** [comment]
Khác otp sao mà sms cũng 1 nội dung đc nhỉ?

**Comment by nqnhat1988** [comment]
cùng otp nha. bấm 2 lần liên tiếp
